### ISSUE TITLE
About the accuracy of circle pattern

### ISSUE THREAD

**Issue by riyueshi** [blackball/SquaredCirclePattern#4]
Hi,
  I got a question about the accuracy of different type of pattern, since the corner of chessboard can be optimized by the intersection of two line and this can make the position of corner very accurate. in your project introduction you mentioned that "The traditional chessboard is not very accurate due to the corner concept, the motion blur from camera, etc". Is there any reference showing that the circle pattern can be more accurate than the chessboard? and what is the method have been used in order to achieve better accuracy in circle pattern.
Thank,
Miller

**Comment by blackball** [comment]
Hi Miller, 

I agree with you that the corners could also be detected accurately, by employing the lines. In the calibration case, we usually need to detect these points from more than 10 image of the patterns, normally, we will hold the pattern by ourselves, then take a video. 

The video could be pretty noisy and may have local highlight, reflection and of course motion blur.     

For each pattern, we hope to locate every desired corners accurately, which will help the later optimization in camera calibration. 

By using line intersection to locate the points, you need to fit a line accurately, and you need to make sure this line has length bigger than a threshold. This will be challenging when there's a big lens distortion or there're an obvious motion blur or there's a highlight on your line, etc. Because you will use some fitting algorithm to estimate the line, sometimes you don't know if the line is accurate enough. 

By using the pattern similar to mine, you need to first locate the blob, then find its edge, then employ ellipse fitting to find its center. Because every circle lies in a pretty small local area, you could use some image processing algorithms to improve the image quality locally to improve the fitting. When you fitting the ellipse, even you have some bad edge points, you could still get a pretty accurate estimation. Another bonus is this method will be more robust to the lens distortion. 

I think the reason why circular pattern is better (and industrial prefer it almost always) is mostly about the practical issues. I found some one did some experiments on this here [1]

Most of the _usable_ camera calibration algorithm are using an iterative routine, which means they will first try to estimate the parameters from the initial images, then use these parameters to transform or undistort the images. It will try the same process again on the images to improve the results, like [2]. The circular pattern also has some advantages in this iterative process.   

Hope this helps. 

---

[1] http://imagine.enpc.fr/~rudakovv/manuscript_main_rudakovv.pdf
[2] https://www.ri.cmu.edu/pub_files/2009/10/Calib.pdf

**Comment by riyueshi** [comment]
Thanks for your detailed illustration, it really helps a lot. I am going to read those two paper in detailed.
